In [1]:
import torch

## Torch Tensors

In [2]:
# 1D tensor
a = torch.tensor([2,2,1])
a

tensor([2, 2, 1])

In [3]:
# 2D tensor
b = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
b

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])

In [4]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
# num of rows
b.shape[0]

4

In [9]:
c = torch.FloatTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
c, c.dtype
#we can also do
#d = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]], dtype = torch.float)

(tensor([[2., 1., 4.],
         [3., 5., 4.],
         [1., 2., 0.],
         [4., 3., 2.]]), torch.float32)

In [8]:
d = torch.DoubleTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
d
#we can also do
#d = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]], dtype = torch.double)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)

In [10]:
print(c.mean())
print(d.mean())
print(c.std())
print(d.std())

tensor(2.5833)
tensor(2.5833, dtype=torch.float64)
tensor(1.5050)
tensor(1.5050, dtype=torch.float64)


In [11]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12)) 

print(b.view(-1,4))
print(b.view(3,4)) #same thing as above

#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


In [12]:
#3d tensor with 2 channels, 3 rows, 4 columns
threed = torch.rand(2, 3, 4)
threed

tensor([[[0.6230, 0.3997, 0.5821, 0.2578],
         [0.0476, 0.5378, 0.9516, 0.2715],
         [0.3062, 0.2178, 0.1702, 0.3884]],

        [[0.6752, 0.0186, 0.5110, 0.4684],
         [0.5379, 0.8035, 0.8501, 0.2432],
         [0.1172, 0.7072, 0.3138, 0.2710]]])

In [14]:
print(threed.view(2, 12))
print(threed.view(2, -1))

tensor([[0.6230, 0.3997, 0.5821, 0.2578, 0.0476, 0.5378, 0.9516, 0.2715, 0.3062,
         0.2178, 0.1702, 0.3884],
        [0.6752, 0.0186, 0.5110, 0.4684, 0.5379, 0.8035, 0.8501, 0.2432, 0.1172,
         0.7072, 0.3138, 0.2710]])
tensor([[0.6230, 0.3997, 0.5821, 0.2578, 0.0476, 0.5378, 0.9516, 0.2715, 0.3062,
         0.2178, 0.1702, 0.3884],
        [0.6752, 0.0186, 0.5110, 0.4684, 0.5379, 0.8035, 0.8501, 0.2432, 0.1172,
         0.7072, 0.3138, 0.2710]])


In [16]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4, 4)
r

tensor([[0.8113, 0.6624, 0.7536, 0.4114],
        [0.5463, 0.1019, 0.5216, 0.2000],
        [0.6077, 0.8920, 0.8944, 0.6291],
        [0.0401, 0.6499, 0.5343, 0.9400]])

In [38]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r = torch.randn(4, 4)
r

tensor([[-0.3805, -0.1179,  2.2641, -0.4277],
        [-0.0887,  0.6032,  0.7002,  0.3291],
        [ 0.2393,  0.2529, -1.1829,  0.4414],
        [ 0.5899,  0.4774, -1.0860,  0.7273]])

In [18]:
intArray = torch.randint(6,10, (5,)) #between 6-9, 10 is exclusive
intArray

tensor([7, 7, 8, 8, 7])

In [20]:
intTensor  = torch.randint(6,10,(3,3)) #2d tensor 3x3
intTensor

tensor([[8, 9, 8],
        [7, 8, 9],
        [8, 9, 9]])

In [21]:
#Get the number of elements in a tensor
torch.numel(intArray), torch.numel(intTensor)

(5, 9)

In [22]:
#3x3 matrix of zeros and dtype long
z = torch.zeros(3, 3, dtype=torch.long)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [26]:
#3x3 matrix of zeros and dtype long
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
rLike = torch.randn_like(r, dtype=torch.double) #get the shape of r
rLike

tensor([[-0.9327,  0.0768, -0.6363,  1.5028],
        [ 1.0130,  0.8971, -1.3920, -0.7901],
        [ 0.6903, -0.1694,  0.1116, -0.3628],
        [ 1.6210, -0.0413,  1.3438, -0.3676]], dtype=torch.float64)

In [40]:
#Addition
r = r.type(torch.DoubleTensor) #casting in order to have the same type and allow addition
#r = r.double() another way of casting
sumatory = torch.add(r, rLike)
sumatory

tensor([[-1.3132, -0.0411,  1.6278,  1.0752],
        [ 0.9242,  1.5003, -0.6919, -0.4610],
        [ 0.9297,  0.0835, -1.0713,  0.0786],
        [ 2.2109,  0.4362,  0.2578,  0.3597]], dtype=torch.float64)

In [41]:
# in place addition
rLike.add_(r)
rLike

tensor([[-1.3132, -0.0411,  1.6278,  1.0752],
        [ 0.9242,  1.5003, -0.6919, -0.4610],
        [ 0.9297,  0.0835, -1.0713,  0.0786],
        [ 2.2109,  0.4362,  0.2578,  0.3597]], dtype=torch.float64)