In [1]:
import torch

## Torch Tensors

In [2]:
# 1D tensor
a = torch.tensor([2,2,1])
a

tensor([2, 2, 1])

In [3]:
# 2D tensor
b = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
b

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])

In [4]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
# num of rows
b.shape[0]

4

In [6]:
c = torch.FloatTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
c, c.dtype
#we can also do
#d = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]], dtype = torch.float)

(tensor([[2., 1., 4.],
         [3., 5., 4.],
         [1., 2., 0.],
         [4., 3., 2.]]), torch.float32)

In [7]:
d = torch.DoubleTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
d
#we can also do
#d = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]], dtype = torch.double)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)

In [8]:
print(c.mean())
print(d.mean())
print(c.std())
print(d.std())

tensor(2.5833)
tensor(2.5833, dtype=torch.float64)
tensor(1.5050)
tensor(1.5050, dtype=torch.float64)


In [9]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12)) 

print(b.view(-1,4))
print(b.view(3,4)) #same thing as above

#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


In [10]:
#3d tensor with 2 channels, 3 rows, 4 columns
threed = torch.rand(2, 3, 4)
threed

tensor([[[0.4583, 0.6582, 0.6351, 0.0189],
         [0.5085, 0.8258, 0.8858, 0.8252],
         [0.4398, 0.2928, 0.5963, 0.9566]],

        [[0.8780, 0.5735, 0.7549, 0.3723],
         [0.6099, 0.1286, 0.1036, 0.2683],
         [0.0506, 0.5551, 0.9716, 0.4214]]])

In [11]:
print(threed.view(2, 12))
print(threed.view(2, -1))

tensor([[0.4583, 0.6582, 0.6351, 0.0189, 0.5085, 0.8258, 0.8858, 0.8252, 0.4398,
         0.2928, 0.5963, 0.9566],
        [0.8780, 0.5735, 0.7549, 0.3723, 0.6099, 0.1286, 0.1036, 0.2683, 0.0506,
         0.5551, 0.9716, 0.4214]])
tensor([[0.4583, 0.6582, 0.6351, 0.0189, 0.5085, 0.8258, 0.8858, 0.8252, 0.4398,
         0.2928, 0.5963, 0.9566],
        [0.8780, 0.5735, 0.7549, 0.3723, 0.6099, 0.1286, 0.1036, 0.2683, 0.0506,
         0.5551, 0.9716, 0.4214]])


In [12]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4, 4)
r

tensor([[0.0061, 0.7192, 0.3030, 0.2828],
        [0.0905, 0.7110, 0.0824, 0.4572],
        [0.1326, 0.5681, 0.2939, 0.0836],
        [0.8965, 0.3797, 0.1460, 0.0222]])

In [13]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r = torch.randn(4, 4)
r

tensor([[-0.7003,  0.8044, -1.8175, -1.5039],
        [ 0.2127, -0.4002,  1.0963, -1.0475],
        [-0.6466,  0.4417, -0.6247,  0.5303],
        [ 0.6649,  1.1404, -0.1515, -1.8854]])

In [14]:
intArray = torch.randint(6,10, (5,)) #between 6-9, 10 is exclusive
intArray

tensor([7, 9, 8, 8, 8])

In [15]:
intTensor  = torch.randint(6,10,(3,3)) #2d tensor 3x3
intTensor

tensor([[9, 6, 9],
        [6, 9, 6],
        [6, 9, 6]])

In [16]:
#Get the number of elements in a tensor
torch.numel(intArray), torch.numel(intTensor)

(5, 9)

In [17]:
#3x3 matrix of zeros and dtype long
z = torch.zeros(3, 3, dtype=torch.long)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [18]:
#3x3 matrix of zeros and dtype long
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
rLike = torch.randn_like(r, dtype=torch.double) #get the shape of r
rLike

tensor([[-0.5141, -0.2497,  1.5027, -0.6339],
        [-0.6122,  1.5297, -1.4059,  0.4259],
        [-0.2453,  1.6736, -1.4996, -1.1938],
        [-0.9354, -0.0240,  0.5453,  0.3008]], dtype=torch.float64)

In [20]:
#Addition
r = r.type(torch.DoubleTensor) #casting in order to have the same type and allow addition
#r = r.double() another way of casting
sumatory = torch.add(r, rLike)
sumatory

tensor([[-1.2144,  0.5547, -0.3148, -2.1378],
        [-0.3995,  1.1295, -0.3095, -0.6216],
        [-0.8920,  2.1153, -2.1243, -0.6635],
        [-0.2705,  1.1165,  0.3939, -1.5846]], dtype=torch.float64)

In [21]:
# in place addition
rLike.add_(r)
rLike

tensor([[-1.2144,  0.5547, -0.3148, -2.1378],
        [-0.3995,  1.1295, -0.3095, -0.6216],
        [-0.8920,  2.1153, -2.1243, -0.6635],
        [-0.2705,  1.1165,  0.3939, -1.5846]], dtype=torch.float64)

## Numpy Bridge


In [22]:
import numpy as np

In [23]:
# To numpy
a = torch.ones(5)
b = a.numpy()

a.add_(1) #b also cahnges its value
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [24]:
#From numpy
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [26]:
#Move the tensor to the GPU
# rLike = rLike.cuda()
rLike

tensor([[-1.2144,  0.5547, -0.3148, -2.1378],
        [-0.3995,  1.1295, -0.3095, -0.6216],
        [-0.8920,  2.1153, -2.1243, -0.6635],
        [-0.2705,  1.1165,  0.3939, -1.5846]], dtype=torch.float64)

In [27]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)
else: 
    print('No cuda available')

False
No cuda available


In [28]:
#from a list to a tensor
a = [2,3,4,1]
print(a)
fromArray = torch.tensor(a)
print(fromArray, fromArray.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [29]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor concatenation

In [30]:
#Tensor Concatenation 
first1 = torch.randn(2, 5)
print(first1)
second1 = torch.randn(3, 5)
print(second1)


tensor([[-0.1281,  0.2077,  0.6434,  0.6092,  1.3423],
        [ 0.5345, -0.0911, -0.6377, -0.4607, -1.2709]])
tensor([[ 0.2101, -0.5845,  0.9153,  0.3139,  0.2874],
        [-0.9421, -0.2007, -0.2877, -0.2076,  0.7694],
        [ 1.2775, -0.4498, -0.6096, -1.2207, -0.2722]])


In [31]:
#Concatenate along the 0 dimension (rows)
con1 = torch.cat([first1, second1])
print('\n')
print(con1)
print('\n')
first2 = torch.randn(2, 3)
print(first2)
second2 = torch.randn(2, 5)
print(second2)
# Concatenate along the 1 dimension (concatenate columns)
con2 = torch.cat([first2, second2], 1)
print('\n')
print(con2)
print('\n')



tensor([[-0.1281,  0.2077,  0.6434,  0.6092,  1.3423],
        [ 0.5345, -0.0911, -0.6377, -0.4607, -1.2709],
        [ 0.2101, -0.5845,  0.9153,  0.3139,  0.2874],
        [-0.9421, -0.2007, -0.2877, -0.2076,  0.7694],
        [ 1.2775, -0.4498, -0.6096, -1.2207, -0.2722]])


tensor([[ 0.8298,  0.3479,  0.9725],
        [ 0.6477, -0.8658,  0.8393]])
tensor([[ 0.4023,  1.5527, -2.1489,  0.0634, -0.5032],
        [ 1.1149, -0.8999, -0.0811, -0.5231,  0.5241]])


tensor([[ 0.8298,  0.3479,  0.9725,  0.4023,  1.5527, -2.1489,  0.0634, -0.5032],
        [ 0.6477, -0.8658,  0.8393,  1.1149, -0.8999, -0.0811, -0.5231,  0.5241]])




## Adding Dimensions to Tensors

In [32]:
#Adds a dimension of 1 along a specified index
tensor1 = torch.tensor([1, 2, 3, 4])
tensorA = torch.unsqueeze(tensor1, 0)
print(tensorA)
print(tensorA.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [34]:
tensorB = torch.unsqueeze(tensor1,1)
print(tensorB)
print(tensorB.shape)
print('\n')
tensor2 = torch.rand(2,3,4)
print(tensor2)
print('\n')
tensorC = tensor2[:,:,2]
print(tensorC)
print(tensorC.shape)
print('\n')
tensorD = torch.unsqueeze(tensorC,2)
print(tensorD)
print(tensorD.shape)

tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.7503, 0.6470, 0.6022, 0.6643],
         [0.2370, 0.0158, 0.4806, 0.2258],
         [0.5205, 0.3667, 0.1339, 0.6370]],

        [[0.5282, 0.9249, 0.4414, 0.4359],
         [0.1719, 0.5890, 0.9490, 0.9444],
         [0.3175, 0.0595, 0.1820, 0.8959]]])


tensor([[0.6022, 0.4806, 0.1339],
        [0.4414, 0.9490, 0.1820]])
torch.Size([2, 3])


tensor([[[0.6022],
         [0.4806],
         [0.1339]],

        [[0.4414],
         [0.9490],
         [0.1820]]])
torch.Size([2, 3, 1])


## Autograd

In [35]:
#If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Since both x and y have their required_grad set to true, therefore we can compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [36]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [37]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [38]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y


False False
None
True


In [39]:
new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

None
True
True
False


In [40]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [41]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
